title: Nick Charlton
email: nick@nickcharlton.net
description: iOS, Mac and Ruby Developer. Amateur Chef.
url: "https://nickcharlton.net"
twitter_username: nickcharlton
github_username: nickcharlton
permalink: /posts/:slug.html
exclude: [Gemfile, Gemfile.lock, deploy.sh]

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

markdown: redcarpet
redcarpet:
  extensions: [smart, tables]
